<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "members:label:newest" => "Am neusten",
"members:label:popular" => "Populär",
"members:label:online" => "Online",
"members:searchname" => "Suchen Sie Mitglieder mit Namen",
"members:searchtag" => "Suchen Sie Mitglieder durch Etikett",
"members:title:searchname" => "Mitgliedsuche für%s",
"members:title:searchtag" => "Mitglieder haben mit etikettiert%s",

   );
   add_translation("de",$language);
   