<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "members:label:newest" => "Il più nuovo",
"members:label:popular" => "Popolare",
"members:label:online" => "In linea",
"members:searchname" => "Ricercare dei membri dal nome",
"members:searchtag" => "Ricercare dei membri dall'etichetta",
"members:title:searchname" => "La ricerca di membro per %s",
"members:title:searchtag" => "I membri hanno etichettato con %s",

   );
   add_translation("it",$language);
   