<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "twitter_api" => "Gezwitscher Wartet",
"twitter_api:requires_oauth" => "Gezwitscher Dienste erfordert, dass die OAuth Bibliotheken plugin ermöglicht wird. ",
"twitter_api:consumer_key" => "Verbrauchertaste",
"twitter_api:consumer_secret" => "Verbrauchergeheimnis",
"twitter_api:settings:instructions" => "Sie müssen eine Verbrauchertaste und Geheimnis von erhalten <a href="https://dev.twitter.com/apps/new" target="_blank">Twitter</a>. Füllen Sie die neue Anwendung Anwendung aus. Wählen Sie „Browser“ als der Anwendungstyp und aus „Vorlesung",
"twitter_api:usersettings:description" => "Verknüpfen Sie Ihres%s Konto mit Twitter. ",
"twitter_api:usersettings:request" => "Sie müssen zuerst <a href=\"%s\">Ermächtigen Sie</a> %s, auf Ihr Twitter Konto zuzugreifen. ",
"twitter_api:usersettings:cannot_revoke" => "Sie können unlink Sie begründen mit Twitter nicht, weil Sie eine E-Mail-Adresse oder Kennwort nicht versorgt haben. <a href=\"%s\">Versorgen Sie sie jetzt</a>. ",
"twitter_api:authorize:error" => "Unfähig, Twitter zu ermächtigen. ",
"twitter_api:authorize:success" => "Gezwitscher greifen Sie auf ist ermächtigt worden zu. ",
"twitter_api:usersettings:authorized" => "Sie haben ermächtigt%s, auf Ihr Twitter Konto zuzugreifen: @%S. ",
	"twitter_api:usersettings:revoke" => "Klicken <a href=\"%s\">Hier</a> Um Zugang zu widerrufen. ",
"twitter_api:usersettings:site_not_configured" => "Ein Verwalter muss zuerst Twitter gestalten, bevor es benutzt werden kann. ",
"twitter_api:revoke:success" => "Gezwitscher greifen Sie auf ist widerrufen worden zu. ",
"twitter_api:login" => "Erlaubt Existieren Benutzer wer hat verbunden ihr Twitter Konto, hinein mit Twitter zu unterzeichnen? ",
"twitter_api:new_users" => "Erlaubt neuen Verbrauchern, um Benutzen von ihrem Twitter Konto anzumelden, selbst wenn Verbraucherregistrierung unwirksam gemacht ist? ",
"twitter_api:login:success" => "Sie sind angemeldet worden. ",
"twitter_api:login:error" => "Unfähig zu Anmeldung mit Twitter. ",
"twitter_api:login:email" => "Sie müssen eine gültige E-Mail-Adresse für Ihr neues eintragen%s Konto. ",
"twitter_api:invalid_page" => "Ungültige Seite",
"twitter_api:deprecated_callback_url" => "Der Authentifizierungsrückruf URL hat für Twitter API zu geändert%s. Bitte bitten Sie Ihren Verwalter, es zu ändern. ",
"twitter_api:interstitial:settings" => "Gestalten Sie Ihre Einstellungen",
"twitter_api:interstitial:description" => "Sie sind fast bereit zu benutzen%s! Wir brauchen ein noch paar Details, bevor Sie fortsetzen können. Diese sind wahlfrei, aber wird Ihnen Anmeldung erlauben, wenn Twitter hinabgeht, oder Sie entscheiden zu unlink Ihren Konten. ",
"twitter_api:interstitial:username" => "Dies ist Ihr Benutzername. Es kann nicht geändert werden. Wenn Sie ein Kennwort setzen, können Sie den Benutzernamen oder Ihre E-Mail-Adresse benutzen, sich anzumelden. ",
"twitter_api:interstitial:name" => "Dies ist die Nameleute werden aufeinander sehen beim Wirken mit Ihnen. ",
"twitter_api:interstitial:email" => "Ihre E-Mail-Adresse. Verbraucher können dies durch Standardwert nicht sehen. ",
"twitter_api:interstitial:password" => "Ein Kennwort zu Anmeldung, wenn Twitter hinunter ist, oder Sie entscheiden zu unlink Ihren Konten. ",
"twitter_api:interstitial:password2" => "Das gleiche Kennwort wieder. ",
"twitter_api:interstitial:no_thanks" => "Kein Dank",
"twitter_api:interstitial:no_display_name" => "Sie müssen einen Ausstellungsnamen haben. ",
"twitter_api:interstitial:invalid_email" => "Sie müssen eine gültige E-Mail-Adresse oder nichts eintragen. ",
"twitter_api:interstitial:existing_email" => "Diese E-Mail-Adresse ist schon auf dieser Stelle registriert. ",
"twitter_api:interstitial:password_mismatch" => "Ihre Kennwörter passen nicht an. ",
"twitter_api:interstitial:cannot_save" => "Kann Kontodetails nicht sparen. ",
"twitter_api:interstitial:saved" => "Kontodetails haben gespart! ",

   );
   add_translation("de",$language);
   