<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "twitter_api" => "Il cinguettio Revisiona",
"twitter_api:requires_oauth" => "Servizi di cinguettio richiedono che il plugin di Biblioteche di OAuth di essere permesso. ",
"twitter_api:consumer_key" => "Chiave di consumatore",
"twitter_api:consumer_secret" => "Segreto di consumatore",
"twitter_api:settings:instructions" => "Lei deve ottenere una chiave di consumatore ed il segreto da <a href="https://dev.twitter.com/apps/new" target="_blank">Cinguettio</a>. Riempire la nuova domanda di appl. Scegliere "Browser" come il tipo di domanda e "di Leggere",
"twitter_api:usersettings:description" => "Collegare il suo %s il conto con il Cinguettio. ",
"twitter_api:usersettings:request" => "Lei deve dapprima <a href=\"%s\">autorizzare</a> %s di accedere il suo conto di Cinguettio. ",
"twitter_api:usersettings:cannot_revoke" => "Lei non può scollegarla considera con Cinguettio perché lei non ha fornito un indirizzo e-mail o una parola d'ordine. <a href=\"%s\">Fornirli ora</a>. ",
"twitter_api:authorize:error" => "Incapace per autorizzare il Cinguettio. ",
"twitter_api:authorize:success" => "L'accesso di cinguettio è stato autorizzato. ",
"twitter_api:usersettings:authorized" => "Lei ha autorizzato %s di accedere il suo conto di Cinguettio: @%S. ",
"twitter_api:usersettings:revoke" => "Scatto <a href=\"%s\">qui</a> Per revocare l'accesso. ",
"twitter_api:usersettings:site_not_configured" => "Un amministratore deve configurare dapprima Cinguettio prima che potesse essere usato. ",
"twitter_api:revoke:success" => "L'accesso di cinguettio è stato revocato. ",
"twitter_api:login" => "Consente gli operatori esistenti chi ha collegato il loro conto di Cinguettio per firmare in con il Cinguettio? ",
"twitter_api:new_users" => "Consente i che nuovi operatori iscriversi per usare il loro conto di Cinguettio anche se iscrizione di operatore è stata incapace? ",
"twitter_api:login:success" => "Lei è stato abbattuto in. ",
"twitter_api:login:error" => "Incapace per accedere con il Cinguettio. ",
"twitter_api:login:email" => "Lei deve entrare un indirizzo e-mail valido per il suo nuovo %s il conto. ",
"twitter_api:invalid_page" => "Pagina di invalido",
"twitter_api:deprecated_callback_url" => "L'URL di richiamata ha cambiato per API di Cinguettio a %s. Per favore di chiedere al suo amministratore di cambiarlo. ",
"twitter_api:interstitial:settings" => "Configurare i suoi montaggi",
"twitter_api:interstitial:description" => "Lei è quasi pronto a usare %s! Abbiamo bisogno di qualche più dettagli prima che lei potesse continuare. Questi sono facoltativi, ma consentirà che lei acceda se Cinguettio scende o lei decide di scollegare i suoi conti. ",
"twitter_api:interstitial:username" => "Questo è il suo nome utente. Non può essere cambiato. Se lei regola una parola d'ordine, lei può usare il nome utente o il suo indirizzo e-mail di abbattere in. ",
"twitter_api:interstitial:name" => "Questa è le persone di nome vedranno quando interagisce con lei. ",
"twitter_api:interstitial:email" => "Il suo indirizzo e-mail. Gli operatori non possono vedere questo dalla mancanza. ",
"twitter_api:interstitial:password" => "Una parola d'ordine di accedere se Cinguettio è giù o lei decide di scollegare i suoi conti. ",
"twitter_api:interstitial:password2" => "La stessa parola d'ordine, di nuovo. ",
"twitter_api:interstitial:no_thanks" => "Nessun ringraziamenti",
"twitter_api:interstitial:no_display_name" => "Lei deve avere un nome di mostra. ",
"twitter_api:interstitial:invalid_email" => "Lei deve entrare un indirizzo e-mail valido o niente. ",
"twitter_api:interstitial:existing_email" => "Quest'indirizzo e-mail è iscritto già su questo luogo. ",
"twitter_api:interstitial:password_mismatch" => "Le sue parole d'ordine non uguagliano. ",
"twitter_api:interstitial:cannot_save" => "Non risparmiarà i dettagli di conto. ",
"twitter_api:interstitial:saved" => "I dettagli di conto hanno risparmiato! ",

   );
   add_translation("it",$language);
   