<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "profile" => "Profilo",
"profile:notfound" => "Spiacente. Non potremmo trovare il profilo richiesto. ",

   );
   add_translation("it",$language);
   