<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "tagcloud:widget:title" => "Etikettieren Sie Wolke",
"tagcloud:widget:description" => "Etikettieren Sie Wolke",
"tagcloud:widget:numtags" => "Zahl von Etiketten, zu zeigen",

   );
   add_translation("de",$language);
   