<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "tagcloud:widget:title" => "Etichettare la Nuvola",
"tagcloud:widget:description" => "Etichettare la nuvola",
"tagcloud:widget:numtags" => "Il numero di etichette di mostrare",

   );
   add_translation("it",$language);
   