<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "admin:administer_utilities:logbrowser" => "Loggen Sie Browser",
"logbrowser" => "Loggen Sie Browser",
"logbrowser:browse" => "Suchen Sie Systemklotz durch",
"logbrowser:search" => "Raffinieren Sie Ergebnisse",
"logbrowser:user" => "Benutzername, durch zu suchen",
"logbrowser:starttime" => "Anfang Zeit (zum Beispiel „letzten Montag“, vor “1 Stunde“)",
"logbrowser:endtime" => "Endzeit",
"logbrowser:explore" => "Erforschen Sie Klotz",
"logbrowser:date" => "Datieren Sie und misst Zeit",
"logbrowser:ip_address" => "IP reden Sie an",
"logbrowser:user:name" => "Verbraucher",
"logbrowser:user:guid" => "Verbraucher GUID",
"logbrowser:object" => "Wenden Sie gegen Typ ein",
"logbrowser:object:guid" => "Wenden Sie gegen GUID ein",
"logbrowser:action" => "Handlung",
"logbrowser:no_result" => "Keine Ergebnisse",

   );
   add_translation("de",$language);
   