<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "admin:administer_utilities:logbrowser" => "Abbattere il browser",
"logbrowser" => "Abbattere il browser",
"logbrowser:browse" => "Curiosare il ceppo di sistema",
"logbrowser:search" => "Raffinare dei risultati",
"logbrowser:user" => "Il nome utente di ricercare da",
"logbrowser:starttime" => 'Il tempo di inizio (per esempio "lunedì scorso", “1 ora fa")',
"logbrowser:endtime" => "Finire il tempo",
"logbrowser:explore" => "Esplorare il ceppo",
"logbrowser:date" => "Datare e cronometrare",
"logbrowser:ip_address" => "Indirizzo di IP",
"logbrowser:user:name" => "Operatore",
"logbrowser:user:guid" => "GUID di operatore",
"logbrowser:object" => "Obbiettare il tipo",
"logbrowser:object:guid" => "Obbiettare GUID",
"logbrowser:action" => "Azione",
"logbrowser:no_result" => "Nessun risultati",

   );
   add_translation("it",$language);
   