<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "admin:develop_tools" => "Werkzeuge",
"admin:develop_tools:preview" => "Theming Sandkasten",
"admin:develop_tools:inspect" => "Prüfen Sie",
"admin:develop_tools:unit_tests" => "Einheit Prüft",
"admin:developers" => "Entwickler",
"admin:developers:settings" => "Einstellungen",
"elgg_dev_tools:settings:explanation" => "Kontrollieren Sie Ihre Entwicklung und Testeinstellungen unten. Einige dieser Einstellungen sind auch verfügbar auf anderen Adminseiten. ",
"developers:label:simple_cache" => "Benutzen Sie einfachen Cachespeicher",
"developers:help:simple_cache" => "Schalten Sie diesen Cachespeicher beim Entwickeln aus. Sonst werden Änderungen zu Ihren CSS und Javascripten ignoriert werden. ",
"developers:label:system_cache" => "Benutzen Sie Systemcachespeicher",
"developers:help:system_cache" => "Schalten Sie dies beim Entwickeln aus. Sonst werden Änderungen in Ihrem plugins nicht registriert werden. ",
"developers:label:debug_level" => "Verfolgen Sie Höhe",
"developers:help:debug_level" => "Dies kontrolliert den Betrag von geloggten Informationen. Siehe elgg_log() für mehr Informationen. ",
"developers:label:display_errors" => "Stellen Sie tödliche PHP Fehler dar",
"developers:help:display_errors" => "Durch Standardwert Elgg. htaccess datei supresses die Ausstellung von schweren Fehlern. ",
"developers:label:screen_log" => "Loggen Sie zum Schirm",
"developers:help:screen_log" => "Dies stellt elgg_log( dar) und elgg_dump() Ausgabe auf der Web-Seite. ",
"developers:label:show_strings" => "Zeigen Sie rohe Übersetzungsschnüre",
"developers:help:show_strings" => "Dies stellt die Übersetzungsschnüre gebraucht durch elgg_echo() dar. ",
"developers:label:wrap_views" => "Hülle sieht an",
"developers:help:wrap_views" => "Dies wickelt fast jeden Blick mit HTML Bemerkungen. Nützlich zur Finden schaffend des Blicks besondere HTML. ",
"developers:label:log_events" => "Loggen Sie Ereignisse und plugin Haken",
"developers:help:log_events" => "Schreiben Sie Ereignisse und plugin Haken zum Klotz. Warnung: es gibt viele von diesen pro Seite. ",
"developers:debug:off" => "Ab",
"developers:debug:error" => "Fehler",
"developers:debug:warning" => "Warnung",
"developers:debug:notice" => "Notiz",
"developers:inspect:help" => "Prüfen Sie Konfiguration von den Elgg Rahmen. ",
"developers:event_log_msg" => "%s: ‘%s,%s‘ hinein%s",
"theme_preview:general" => "Einführung",
"theme_preview:breakout" => "Brechen Sie von iframe aus",
"theme_preview:buttons" => "Knöpfe",
"theme_preview:components" => "Teile",
"theme_preview:forms" => "Formen",
"theme_preview:grid" => "Raster",
"theme_preview:icons" => "Abbilder",
"theme_preview:modules" => "Moduln",
"theme_preview:navigation" => "Navigation",
"theme_preview:typography" => "Typografie",
"theme_preview:miscellaneous" => "Verschieden",
"developers:unit_tests:description" => "Elgg hat Einheit und Integrationsprüfungen für Entdeckenwanzen in seinen Kernklassen und Funktionen. ",
"developers:unit_tests:warning" => "Warnung: Laufen Sie nicht Diese Prüfungen auf eine Produktionsstelle. Sie können Ihre Datenbank verderben. ",
"developers:unit_tests:run" => "Lauf",
"developers:settings:success" => "Einstellungen haben gespart",

   );
   add_translation("de",$language);
   