<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "admin:develop_tools" => "Attrezzi",
"admin:develop_tools:preview" => "Buca di sabbia di Theming",
"admin:develop_tools:inspect" => "Ispezionare",
"admin:develop_tools:unit_tests" => "L'unità Testa",
"admin:developers" => "Sviluppatori",
"admin:developers:settings" => "Montaggi",
"elgg_dev_tools:settings:explanation" => "Controllare i suoi montaggi di sviluppo e debugging di sotto. Alcuni di questi montaggi sono anche disponibili sulle altre pagine di ammin. ",
"developers:label:simple_cache" => "Usare il nascondiglio semplice",
"developers:help:simple_cache" => "Spegnere questo nascondiglio quando sviluppa. Altrimenti, i cambiamenti al suo CSS e Linguaggio javascript saranno ignorati. ",
"developers:label:system_cache" => "Usare il nascondiglio di sistema",
"developers:help:system_cache" => "Spegnere questo quando sviluppa. Altrimenti, i cambiamenti nel suo plugins non saranno iscritti. ",
"developers:label:debug_level" => "Tracciare il livello",
"developers:help:debug_level" => "Questo controlla l'ammontare di informazioni abbattute. Vedere l'elgg_log() per più informazioni. ",
"developers:label:display_errors" => "Mostrare gli errori di PHP fatali",
"developers:help:display_errors" => "Dalla mancanza, Elgg. il supresses di file di htaccess la mostra di errori fatali. ",
"developers:label:screen_log" => "Abbattere allo schermo",
"developers:help:screen_log" => "Questo mostra l'elgg_log() e l'elgg_dump() l'uscita sulla pagina web. ",
"developers:label:show_strings" => "Mostrare le cordicelle di traduzione crude",
"developers:help:show_strings" => "Questo mostra le cordicelle di traduzione usate da elgg_echo(). ",
"developers:label:wrap_views" => "Avvolgere delle vedute",
"developers:help:wrap_views" => "Questo avvolge quasi ogni veduta con i commenti di HTML. Utile per trovare la veduta che crea HTML particolare. ",
"developers:label:log_events" => "Abbattere dei ganci di avvenimenti e plugin",
"developers:help:log_events" => "Scrivere dei ganci di avvenimenti e plugin al ceppo. L'avvertimento: ci sono molti di questi per la pagina. ",
"developers:debug:off" => "Via da",
"developers:debug:error" => "Errore",
"developers:debug:warning" => "Avvertimento",
"developers:debug:notice" => "Avviso",
"developers:inspect:help" => "Ispezionare la configurazione della struttura di Elgg. ",
"developers:event_log_msg" => "%s: ‘%s, %s' in %s",
"theme_preview:general" => "Introduzione",
"theme_preview:breakout" => "Fuggire di iframe",
"theme_preview:buttons" => "Bottoni",
"theme_preview:components" => "Componenti",
"theme_preview:forms" => "Forme",
"theme_preview:grid" => "Griglia",
"theme_preview:icons" => "Icone",
"theme_preview:modules" => "Moduli",
"theme_preview:navigation" => "Navigazione",
"theme_preview:typography" => "Tipografia",
"theme_preview:miscellaneous" => "Miscellaneo",
"developers:unit_tests:description" => "Elgg ha i test di unità ed integrazione per rilevare di insetti nelle sue classi di centro e le funzioni. ",
"developers:unit_tests:warning" => "L'avvertimento: Non Correre Questi Test su un Luogo di Produzione. Possono corrompere la sua base di dati. ",
"developers:unit_tests:run" => "Correre",
"developers:settings:success" => "I montaggi hanno risparmiato",

   );
   add_translation("it",$language);
   