<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "search:enter_term" => "Tragen Sie einen Suchenbegriff ein: ",
"search:no_results" => "Keine Ergebnisse. ",
"search:matched" => "Angepasst: ",
"search:results" => "Ergebnisse für%s",
"search:no_query" => "Bitte tragen Sie eine Frage ein, zu suchen. ",
"search:search_error" => "Fehler",
"search:more" => "%s mehr%s",
"search_types:tags" => "Etikette",
"search_types:comments" => "Bemerkungen",
"search:comment_on" => "Kommentieren Sie auf „%s“",
"search:comment_by" => "Durch",
"search:unavailable_entity" => "Nicht verfügbares Wesen",

   );
   add_translation("de",$language);
   