<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "search:enter_term" => "Entrare un termine di ricerca: ",
"search:no_results" => "Nessun risultati. ",
"search:matched" => "Uguagliato: ",
"search:results" => "I risultati per %s",
"search:no_query" => "Per favore di entrare un quesito per ricercare. ",
"search:search_error" => "Errore",
"search:more" => "%s più %s",
"search_types:tags" => "Etichette",
"search_types:comments" => "Commenti",
"search:comment_on" => "Commentare „%s“",
"search:comment_by" => "da",
"search:unavailable_entity" => "Entità non disponibile",

   );
   add_translation("it",$language);
   