<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "expages" => "Stelle paginiert",
"admin:appearance:expages" => "Stelle Paginiert",
"expages:about" => "Um",
"expages:terms" => "Begriffe",
"expages:privacy" => "Ruhe",
"expages:contact" => "Kontakt",
"expages:notset" => "Diese Seite ist nicht noch aufgestellt worden. ",
"expages:posted" => "Ihre Seite wurde erfolgreich aktualisiert. ",
"expages:error" => "Unfähig, diese Seite zu sparen. ",

   );
   add_translation("de",$language);
   