<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "expages" => "Il luogo chiama",
"admin:appearance:expages" => "Il luogo Chiama",
"expages:about" => "Di",
"expages:terms" => "Termini",
"expages:privacy" => "Intimità",
"expages:contact" => "Contatto",
"expages:notset" => "Questa pagina non è stata preparata ancora. ",
"expages:posted" => "La sua pagina è stata aggiornata con successo. ",
"expages:error" => "Incapace per risparmiare questa pagina. ",

   );
   add_translation("it",$language);
   