<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "file" => "Dateien",
"file:user" => "%die Dateien von s",
"file:friends" => "Die Dateien von Freunden",
"file:all" => "Alle Stelle legt ab",
"file:edit" => "Redigieren Sie Datei",
"file:more" => "Mehr Dateien",
"file:list" => "Führen Sie Blick auf",
"file:group" => "Gruppendateien",
"file:gallery" => "Galerieblick",
"file:gallery_list" => "Galerie oder Liste sehen an",
"file:num_files" => "Zahl von Dateien, darzustellen",
"file:user:gallery" => "Siehe an%s Galerie",
"file:upload" => "Laden Sie eine Datei",
"file:replace" => "Ersetzen Sie Dateieninhalt (Blattlücke, Datei nicht zu ändern)",
"file:list:title" => "%s%s%s",
"file:title:friends" => "Freunde",
"file:add" => "Laden Sie eine Datei",
"file:file" => "Datei",
"file:title" => "Titel",
"file:desc" => "Beschreibung",
"file:tags" => "Etikette",
"file:list:list" => "Schalten Sie zum Listenblick",
"file:list:gallery" => "Schalten Sie zum Galerieblick",
"file:types" => "Geladen legt Typen ab",
"file:type:" => "Dateien",
"file:type:all" => "Alle Dateien",
"file:type:video" => "Videos",
"file:type:document" => "Dokumente",
"file:type:audio" => "Ton",
"file:type:image" => "Bilder",
"file:type:general" => "General",
"file:user:type:video" => "%die Videos von s",
"file:user:type:document" => "%die Dokumente von s",
"file:user:type:audio" => "%s Ton",
"file:user:type:image" => "%die Bilder von s",
"file:user:type:general" => "%der General von s ablegt",
"file:friends:type:video" => "Die Videos Ihrer Freunde",
"file:friends:type:document" => "Die Dokumente Ihrer Freunde",
"file:friends:type:audio" => "Der Ton Ihrer Freunde",
"file:friends:type:image" => "Die Bilder Ihrer Freunde",
"file:friends:type:general" => "Der General Ihrer Freunde legt ab",
"file:widget" => "Dateiprodukt",
"file:widget:description" => "Präsentieren Sie Ihre spätesten Dateien",
"groups:enablefiles" => "Ermöglichen Sie Gruppendateien",
"file:download" => "Laden Sie dies",
"file:delete:confirm" => "Sind Sie sicher Sie löschen wollen diese Datei? ",
"file:tagcloud" => "Etikettieren Sie Wolke",
"file:display:number" => "Zahl von Dateien, darzustellen",
"river:create:object:file" => "%s hat geladen die Datei%s",
"river:comment:object:file" => "%s hat kommentiert auf der Datei%s",
"item:object:file" => "Dateien",
"file:newupload" => "Eine neue Datei ist geladen worden",
"file:notification" => "%s hat geladen eine neue Datei: 

%s%s

Blick und kommentiert auf der neuen Datei: %s

",
"file:embed" => "Betten Sie Medien ein",
"file:embedall" => "Alle",
"file:saved" => "Ihre Datei wurde erfolgreich gespart. ",
"file:deleted" => "Ihre Datei wurde erfolgreich gelöscht. ",
"file:none" => "Keine Dateien. ",
"file:uploadfailed" => "Traurig; wir könnten Ihre Datei nicht sparen. ",
"file:downloadfailed" => "Traurig; diese Datei ist nicht verfügbar zurzeit. ",
"file:deletefailed" => "Ihre Datei könnte nicht zurzeit gelöscht werden. ",
"file:noaccess" => "Sie haben nicht Erlaubnis, diese Datei zu ändern",
"file:cannotload" => "Es gab einen Fehler, der die Datei lädt",
"file:nofile" => "Sie müssen eine Datei auswählen",

   );
   add_translation("de",$language);
   