<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "file" => "File",
"file:user" => "%s scheda",
"file:friends" => "File di amici",
"file:all" => "Tutto il luogo scheda",
"file:edit" => "Redigere il file",
"file:more" => "Più file",
"file:list" => "elencare la veduta",
"file:group" => "Il gruppo scheda",
"file:gallery" => "veduta di galleria",
"file:gallery_list" => "La galleria o l'elenco osservano",
"file:num_files" => "Il numero di file di mostrare",
"file:user:gallery" => "Osservare %s la galleria",
"file:upload" => "Caricare un file",
"file:replace" => "Sostituire il contenuto di file (lo spazio vuoto di congedo non di cambiare il file)",
"file:list:title" => "%s %s %s",
"file:title:friends" => "Amici",
"file:add" => "Caricare un file",
"file:file" => "File",
"file:title" => "Titolo",
"file:desc" => "Descrizione",
"file:tags" => "Etichette",
"file:list:list" => "Commutare alla veduta di elenco",
"file:list:gallery" => "Commutare alla veduta di galleria",
"file:types" => "Ha caricato i tipi di file",
"file:type:" => "File",
"file:type:all" => "Tutti i file",
"file:type:video" => "Video",
"file:type:document" => "Documenti",
"file:type:audio" => "Audio",
"file:type:image" => "Immagini",
"file:type:general" => "Generale",
"file:user:type:video" => "%s videoregistra",
"file:user:type:document" => "%s documenta",
"file:user:type:audio" => "%s audio",
"file:user:type:image" => "%s dipinge",
"file:user:type:general" => "%s i file generali",
"file:friends:type:video" => "I video dei suoi amici",
"file:friends:type:document" => "I documenti dei suoi amici",
"file:friends:type:audio" => "I suoi amici audio",
"file:friends:type:image" => "Le immagini dei suoi amici",
"file:friends:type:general" => "I suoi amici generali schedano",
"file:widget" => "Schedare il prodotto promozionale",
"file:widget:description" => "La bacheca i suoi file recentissimi",
"groups:enablefiles" => "Permettere i file di gruppo",
"file:download" => "Scaricare questo",
"file:delete:confirm" => "Lei è sicuro che lei vuole cancellare questo file? ",
"file:tagcloud" => "Etichettare la nuvola",
"file:display:number" => "Il numero di file di mostrare",
"river:create:object:file" => "%s ha caricato il file %s",
"river:comment:object:file" => "%s ha commentato il file %s",
"item:object:file" => "File",
"file:newupload" => "Un nuovo file è stato caricato",
"file:notification" => "%s ha caricato un nuovo file: 

%s %s

La veduta e commenta il nuovo file: %s

",
"file:embed" => "Incassare dei mezzi di comunicazione",
"file:embedall" => "Tutto",
"file:saved" => "Il suo file è stato risparmiato con successo. ",
"file:deleted" => "Il suo file è stato cancellato con successo. ",
"file:none" => "Nessun file. ",
"file:uploadfailed" => "Spiacente; non potremmo risparmiare il suo file. ",
"file:downloadfailed" => "Spiacente; questo file non è disponibile a questo tempo. ",
"file:deletefailed" => "Il suo file non potrebbe essere cancellato a questo tempo. ",
"file:noaccess" => "Lei non ha dei permessi per cambiare questo file",
"file:cannotload" => "C'era un errore che carica il file",
"file:nofile" => "Lei deve scegliere un file",

   );
   add_translation("it",$language);
   