<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "admin:users:unvalidated" => "Unvalidated",
"email:validate:subject" => "%s bitte bestätigen Ihre E-Mail-Adresse für%s! ",
"email:validate:body" => "%s,

Bevor Sie Sie anfangen können, zu benutzen%s, müssen Sie Ihre E-Mail-Adresse bestätigen. 

Bitte bestätigen Sie Ihre E-Mail-Adresse durch Anklicken der Verbindung unten: 

%s

Wenn Sie die Verbindung, Kopie nicht anklicken können, und fügen Sie es zu Ihrem Browser manuell ein. 

%s%s

",
"email:confirm:success" => "Sie haben Ihre E-Mail-Adresse bestätigt! ",
"email:confirm:fail" => "Ihre E-Mail-Adresse könnte nicht beglaubigt werden... ",
"uservalidationbyemail:registerok" => "Um Ihr Konto zu aktivieren, bitte bestätigen Sie, dass Ihre E-Mail-Adresse durch Anklicken der Verbindung wir nur Sie geschickt haben. ",
"uservalidationbyemail:login:fail" => "Ihr Konto ist so der Klotz in versagtem Versuch nicht bestätigt. Eine andere Gültigkeitserklärungse-Mail ist geschickt worden. ",
"uservalidationbyemail:admin:no_unvalidated_users" => "Nein unvalidated Verbraucher. ",
"uservalidationbyemail:admin:unvalidated" => "Unvalidated",
"uservalidationbyemail:admin:user_created" => "Eingetragen%s",
"uservalidationbyemail:admin:resend_validation" => "Senden Sie erneut Gültigkeitserklärung",
"uservalidationbyemail:admin:validate" => "Bestätigen Sie",
"uservalidationbyemail:admin:delete" => "Löschen Sie",
"uservalidationbyemail:confirm_validate_user" => "Bestätigen Sie%s? ",
"uservalidationbyemail:confirm_resend_validation" => "Sendet erneut Gültigkeitserklärungse-Mail zu%s? ",
"uservalidationbyemail:confirm_delete" => "Löschen Sie%s? ",
"uservalidationbyemail:confirm_validate_checked" => "Bestätigt geprüfte Verbraucher? ",
"uservalidationbyemail:confirm_resend_validation_checked" => "Sendet erneut Gültigkeitserklärung zu geprüften Verbrauchern? ",
"uservalidationbyemail:confirm_delete_checked" => "Löscht geprüfte Verbraucher? ",
"uservalidationbyemail:check_all" => "Alle",
"uservalidationbyemail:errors:unknown_users" => "Unbekannte Verbraucher",
"uservalidationbyemail:errors:could_not_validate_user" => "Könnte Verbraucher nicht bestätigen. ",
"uservalidationbyemail:errors:could_not_validate_users" => "Könnte alle geprüften Verbraucher nicht bestätigen. ",
"uservalidationbyemail:errors:could_not_delete_user" => "Könnte Verbraucher nicht löschen. ",
"uservalidationbyemail:errors:could_not_delete_users" => "Könnte alle geprüften Verbraucher nicht löschen. ",
"uservalidationbyemail:errors:could_not_resend_validation" => "Könnte erneut Gültigkeitserklärungsbitte nicht senden. ",
"uservalidationbyemail:errors:could_not_resend_validations" => "Könnte erneut alle Gültigkeitserklärungsbitten zu geprüften Verbrauchern nicht senden. ",
"uservalidationbyemail:messages:validated_user" => "Verbraucher hat bestätigt. ",
"uservalidationbyemail:messages:validated_users" => "Alle geprüften Verbraucher haben bestätigt. ",
"uservalidationbyemail:messages:deleted_user" => "Verbraucher hat gelöscht. ",
"uservalidationbyemail:messages:deleted_users" => "Alle geprüften Verbraucher haben gelöscht. ",
"uservalidationbyemail:messages:resent_validation" => "Gültigkeitserklärungsbitte nehmen Sie übel. ",
"uservalidationbyemail:messages:resent_validations" => "Gültigkeitserklärungsbitten nehmen übel zu allen geprüften Verbrauchern. ",

   );
   add_translation("de",$language);
   