<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "admin:users:unvalidated" => "Unvalidated",
"email:validate:subject" => "%s conferma per favore il suo indirizzo e-mail per %s! ",
"email:validate:body" => "%s,

Prima che lei potesse cominciarla usando %s, lei deve confermare il suo indirizzo e-mail. 

Per favore di confermare il suo indirizzo e-mail scattando sulla maglia di sotto: 

%s

Se lei non può scattare sulla maglia, la copia e l'incolla al suo browser a mano. 

%s %s

",
"email:confirm:success" => "Lei ha confermato il suo indirizzo e-mail! ",
"email:confirm:fail" => "Il suo indirizzo e-mail non potrebbe essere verificato... ",
"uservalidationbyemail:registerok" => "Per attivare il suo conto, per favore di confermare il suo indirizzo e-mail scattando sulla maglia l'abbiamo inviato appena. ",
"uservalidationbyemail:login:fail" => "Il suo conto non è convalidato così il ceppo nel tentativo fallito. Un'altra e-mail di convalidazione è stata inviata. ",
"uservalidationbyemail:admin:no_unvalidated_users" => "No unvalidated gli operatori. ",
"uservalidationbyemail:admin:unvalidated" => "Unvalidated",
"uservalidationbyemail:admin:user_created" => "Iscritto %s",
"uservalidationbyemail:admin:resend_validation" => "Inviare di nuovo la convalidazione",
"uservalidationbyemail:admin:validate" => "Convalidare",
"uservalidationbyemail:admin:delete" => "Cancellare",
"uservalidationbyemail:confirm_validate_user" => "Convalida %s? ",
"uservalidationbyemail:confirm_resend_validation" => "Invia di nuovo l'e-mail di convalidazione a %s? ",
"uservalidationbyemail:confirm_delete" => "Cancella %s? ",
"uservalidationbyemail:confirm_validate_checked" => "Convalida gli operatori controllati? ",
"uservalidationbyemail:confirm_resend_validation_checked" => "Invia di nuovo la convalidazione agli operatori controllati? ",
"uservalidationbyemail:confirm_delete_checked" => "Cancella gli operatori controllati? ",
"uservalidationbyemail:check_all" => "Tutto",
"uservalidationbyemail:errors:unknown_users" => "Operatori sconosciuti",
"uservalidationbyemail:errors:could_not_validate_user" => "Non potrebbe convalidare l'operatore. ",
"uservalidationbyemail:errors:could_not_validate_users" => "Non potrebbe convalidare tutti gli operatori controllati. ",
"uservalidationbyemail:errors:could_not_delete_user" => "Non potrebbe cancellare l'operatore. ",
"uservalidationbyemail:errors:could_not_delete_users" => "Non potrebbe cancellare tutti gli operatori controllati. ",
"uservalidationbyemail:errors:could_not_resend_validation" => "Non potrebbe inviare di nuovo la richiesta di convalidazione. ",
"uservalidationbyemail:errors:could_not_resend_validations" => "Non potrebbe inviare di nuovo tutte le richieste di convalidazione agli operatori controllati. ",
"uservalidationbyemail:messages:validated_user" => "L'operatore ha convalidato. ",
"uservalidationbyemail:messages:validated_users" => "Tutti gli operatori controllati hanno convalidato. ",
"uservalidationbyemail:messages:deleted_user" => "L'operatore ha cancellato. ",
"uservalidationbyemail:messages:deleted_users" => "Tutti gli operatori controllati hanno cancellato. ",
"uservalidationbyemail:messages:resent_validation" => "La richiesta di convalidazione si risente di. ",
"uservalidationbyemail:messages:resent_validations" => "Le richieste di convalidazione si risentono di a tutti gli operatori controllati. ",

   );
   add_translation("it",$language);
   