<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "thewire" => "Der Draht",
"thewire:everyone" => "Alle Draht stellt auf",
"thewire:user" => "%der Draht von s aufstellt",
"thewire:friends" => "Der Draht von Freunden stellt auf",
"thewire:reply" => "Antwort",
"thewire:replying" => "Erwiderung zu%s (@%s) der geschrieben hat",
"thewire:thread" => "Faden",
"thewire:charleft" => "Charaktere bleibend",
"thewire:tags" => "Drahtposten haben mit „%s“ etikettiert",
"thewire:noposts" => "Kein Draht stellt noch auf",
"item:object:thewire" => "Draht stellt auf",
"thewire:update" => "Aktualisierung",
"thewire:by" => "Verdrahten Sie Posten durch%s",
"thewire:previous" => "Vorherig",
"thewire:hide" => "Haut",
"thewire:previous:help" => "Siehe vorherigen Posten an",
"thewire:hide:help" => "Verstecken Sie vorherigen Posten",
"river:create:object:thewire" => "%s hat aufgestellt zum%s",
"thewire:wire" => "Draht",
"thewire:widget:desc" => "Stellen Sie Ihre spätesten Drahtposten dar",
"thewire:num" => "Zahl von Posten, darzustellen",
"thewire:moreposts" => "Mehr Draht stellt auf",
"thewire:posted" => "Ihre Nachricht wurde erfolgreich zum Draht aufgestellt. ",
"thewire:deleted" => "Der Drahtposten wurde erfolgreich gelöscht. ",
"thewire:blank" => "Traurig, Sie müssen einen Text eintragen, bevor wir dies aufstellen können. ",
"thewire:notfound" => "Traurig, könnten wir den angegebenen Drahtposten nicht finden. ",
"thewire:notdeleted" => "Traurig. Wir könnten diesen Drahtposten nicht löschen. ",
"thewire:notify:subject" => "Neuer Drahtposten",
"thewire:notify:reply" => "%s hat geantwortet auf%s auf dem Draht: ",
"thewire:notify:post" => "%s hat aufgestellt auf dem Draht: ",

   );
   add_translation("de",$language);
   