<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "thewire" => "Il Filo Metallico",
"thewire:everyone" => "Tutto il filo metallico affigge",
"thewire:user" => "%s il filo metallico affigge",
"thewire:friends" => "Il filo metallico degli amici affigge",
"thewire:reply" => "Risposta",
"thewire:replying" => "Rispondere a %s (@%s) che ha scritto",
"thewire:thread" => "Filo",
"thewire:charleft" => "i caratteri che rimangono",
"thewire:tags" => "I pali di filo metallico hanno etichettato con „%s“",
"thewire:noposts" => "Non affigge alcun filo metallico ancora",
"item:object:thewire" => "Il filo metallico affigge",
"thewire:update" => "Aggiornamento",
"thewire:by" => "Cablare il palo da %s",
"thewire:previous" => "Precedente",
"thewire:hide" => "Nascondiglio",
"thewire:previous:help" => "Osservare il palo precedente",
"thewire:hide:help" => "Nascondere il palo precedente",
"river:create:object:thewire" => "%s ha affisso al %s",
"thewire:wire" => "filo metallico",
"thewire:widget:desc" => "Mostrare i suoi pali di filo metallico recentissimi",
"thewire:num" => "Il numero di pali di mostrare",
"thewire:moreposts" => "Più filo metallico affigge",
"thewire:posted" => "Il suo messaggio è stato affisso con successo al filo metallico. ",
"thewire:deleted" => "Il palo di filo metallico è stato cancellato con successo. ",
"thewire:blank" => "Spiacente, lei deve entrare alcuno testo prima che potessimo affiggere questo. ",
"thewire:notfound" => "Spiacente, non potremmo trovare il palo di filo metallico specificato. ",
"thewire:notdeleted" => "Spiacente. Non potremmo cancellare questo palo di filo metallico. ",
"thewire:notify:subject" => "Il nuovo palo di filo metallico",
"thewire:notify:reply" => "%s ha risposto a %s sul filo metallico: ",
"thewire:notify:post" => "%s ha affisso sul filo metallico: ",

   );
   add_translation("it",$language);
   