<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "messageboard:board" => "Nachrichtausschuss",
"messageboard:messageboard" => "Nachrichtausschuss",
"messageboard:viewall" => "Siehe alle an",
"messageboard:postit" => "Posten",
"messageboard:history:title" => "Geschichte",
"messageboard:none" => "Es gibt nichts auf diesem Nachrichtausschuss noch",
"messageboard:num_display" => "Zahl von Nachrichten, darzustellen",
"messageboard:desc" => "Dies ist ein Nachrichtausschuss, den Sie auf Ihr Profil stellen können, wo andere Verbraucher kommentieren können. ",
"messageboard:user" => "%der Nachrichtausschuss von s",
"messageboard:replyon" => "Antworten Sie an",
"messageboard:history" => "Geschichte",
"messageboard:owner" => "%der Nachrichtausschuss von s",
"messageboard:owner_history" => "%die Posten von s an%der Nachrichtausschuss von s",
"river:messageboard:user:default" => "%s hat aufgestellt an%der Nachrichtausschuss von s",
"messageboard:posted" => "Sie haben erfolgreich auf dem Nachrichtausschuss aufgestellt. ",
"messageboard:deleted" => "Sie haben erfolgreich die Nachricht gelöscht. ",
"messageboard:email:subject" => "Sie haben eine neue Nachrichtausschussbemerkung! ",
"messageboard:email:body" => "Sie haben eine neue Nachrichtausschussbemerkung von%s. Es liest: 

%s

Um Ihre Nachrichtausschussbemerkungen anzusehen, Klicken hier: 

%s

Anzusehen%das Profil von s, Klicken hier: 

%s

Sie können zu dieser E-Mail nicht antworten. 

",
"messageboard:blank" => "Traurig; Sie brauchen tatsächlich, etwas ins Nachrichtgebiet zu stellen, bevor wir es sparen können. ",
"messageboard:notfound" => "Traurig; wir könnten das angegebene Ding nicht finden. ",
"messageboard:notdeleted" => "Traurig; wir könnten diese Nachricht nicht löschen. ",
"messageboard:somethingwentwrong" => "Etwas ist schief gegangen beim Versuchen, Ihre Nachricht zu sparen, vergewissert sich, dass Sie tatsächlich eine Nachricht geschrieben haben. ",
"messageboard:failure" => "Ein unerwarteter Fehler hat beim Hinzufügen Ihrer Nachricht stattgefunden. Bitte versuchen Sie wieder. ",

   );
   add_translation("de",$language);
   