<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "messageboard:board" => "Asse di messaggio",
"messageboard:messageboard" => "asse di messaggio",
"messageboard:viewall" => "Osservare tutto",
"messageboard:postit" => "Palo",
"messageboard:history:title" => "Storia",
"messageboard:none" => "Ci non è niente su quest'asse di messaggio ancora",
"messageboard:num_display" => "Il numero di messaggi di mostrare",
"messageboard:desc" => "Questa è un'asse di messaggio che lei può indossare il suo profilo dove gli altri operatori possono commentare. ",
"messageboard:user" => "%s l'asse di messaggio",
"messageboard:replyon" => "rispondere su",
"messageboard:history" => "storia",
"messageboard:owner" => "%s l'asse di messaggio",
"messageboard:owner_history" => "%s affigge su %s l'asse di messaggio",
"river:messageboard:user:default" => "%s ha affisso su %s l'asse di messaggio",
"messageboard:posted" => "Lei ha affisso con successo sull'asse di messaggio. ",
"messageboard:deleted" => "Lei ha cancellato con successo il messaggio. ",
"messageboard:email:subject" => "Lei ha un nuovo commento di asse di messaggio! ",
"messageboard:email:body" => "Lei ha un nuovo commento di asse di messaggio da %s. Legge: 

%s

Per osservare i suoi commenti di asse di messaggio, lo scatto qui: 

%s

Per osservare %s il profilo, lo scatto qui: 

%s

Lei non può rispondere a quest'e-mail. 

",
"messageboard:blank" => "Spiacente; lei ha bisogno di effettivamente mettere qualcosa nell'area di messaggio prima che potessimo risparmiarlo. ",
"messageboard:notfound" => "Spiacente; non potremmo trovare l'articolo specificato. ",
"messageboard:notdeleted" => "Spiacente; non potremmo cancellare questo messaggio. ",
"messageboard:somethingwentwrong" => "Qualcosa è andato male quando prova a risparmiare il suo messaggio, la sua marca sicura lei ha scritto effettivamente un messaggio. ",
"messageboard:failure" => "Un errore imprevisto è accaduto quando aggiunge il suo messaggio. Per favore di provare di nuovo. ",

   );
   add_translation("it",$language);
   