<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "garbagecollector:period" => "Wie oft sollte der Elgg Müllsammler laufen? ",
"garbagecollector:weekly" => "Nachdem eine Woche",
"garbagecollector:monthly" => "Nachdem einen Monat",
"garbagecollector:yearly" => "Nachdem ein Jahr",
"garbagecollector" => "Müll SAMMLER",
"garbagecollector:done" => "GEMACHT",
"garbagecollector:optimize" => "Optimieren%s",
"garbagecollector:error" => "FEHLER",
"garbagecollector:ok" => "ZUSTIMMUNG",
"garbagecollector:gc:metastrings" => "Aufräumen unlinked metastrings: ",

   );
   add_translation("de",$language);
   