<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "garbagecollector:period" => "Come spesso lo spazzino di Elgg dovrebbe correre? ",
"garbagecollector:weekly" => "Una volta alla settimana",
"garbagecollector:monthly" => "Una volta al mese",
"garbagecollector:yearly" => "Una volta all'anno",
"garbagecollector" => "SPAZZINO",
"garbagecollector:done" => "FATTO",
"garbagecollector:optimize" => "Ottimizzare %s",
"garbagecollector:error" => "ERRORE",
"garbagecollector:ok" => "OK",
"garbagecollector:gc:metastrings" => "Pulire il metastrings scollegato: ",

   );
   add_translation("it",$language);
   