<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "categories" => "Kategorien",
"categories:settings" => "Feste Stellenkategorien",
"categories:explanation" => "Um einige vordefinierten Stelle-breiten Kategorien zu setzen, die durch Ihr System benutzt werden werden, tragen Sie sie unten, getrennt mit Kommas ein. Vereinbare Werkzeuge werden dann sie, wenn der Verbraucher schafft, darstellen oder redigiert Inhalt. ",
"categories:save:success" => "Stellenkategorien wurden erfolgreich gespart. ",
"categories:results" => "Ergebnisse für die Stellenkategorie: %s",
"categories:on_activate_reminder" => "Stelle-breite Kategorien werden nicht arbeiten, bis Sie Kategorien hinzufügen. <a href=\"%s\">Fügen Sie Kategorien jetzt hinzu.</a>",

   );
   add_translation("de",$language);
   