<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "categories" => "Categorie",
"categories:settings" => "Le categorie di luogo regolando",
"categories:explanation" => "Per regolare alcune categorie predefiniti luogo-larghi che sarà usato in ogni parte il suo sistema, entrarli di sotto, separato con le virgole. Gli attrezzi compatibili li mostreranno poi quando l'operatore crea o redige il contenuto. ",
"categories:save:success" => "Le categorie di luogo sono state risparmiate con successo. ",
"categories:results" => "I risultati per la categoria di luogo: %s",
"categories:on_activate_reminder" => "Categorie luogo-larghi non lavoreranno finché lei aggiunge delle categorie. <a href=\"%s\">Aggiungere delle categorie ora.</a>",

   );
   add_translation("it",$language);
   