<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "friends:all" => "Alle Freunde",
"notifications:subscriptions:personal:description" => "Empfangen Sie Notifikationen, wenn Handlungen auf Ihrem Inhalt durchgeführt sind",
"notifications:subscriptions:personal:title" => "Persönliche Notifikationen",
"notifications:subscriptions:friends:title" => "Freunde",
"notifications:subscriptions:friends:description" => "Unten sind Sammlungen von Ihren Freunden. Auswählen einer Sammlung schaltet Notifikationen für die Verbraucher in jener Sammlung ein. ",
"notifications:subscriptions:collections:edit" => "Um Ihre geteilten Zugriffsnotifikationen zu redigieren, Klicken hier. ",
"notifications:subscriptions:changesettings" => "Notifikationen",
"notifications:subscriptions:changesettings:groups" => "Gruppennotifikationen",
"notifications:subscriptions:title" => "Notifikationen pro Verbraucher",
"notifications:subscriptions:description" => "Um Notifikationen von Ihren Freunden (auf einer einzelnen Basis) zu empfangen, wenn sie neuen Inhalt schaffen, finden Sie sie unten und wählen Sie die Notifikationsmethode aus, die Sie benutzen möchten. ",
"notifications:subscriptions:groups:description" => "Um Notifikationen zu empfangen, wenn neuer Inhalt zu eine Gruppe hinzugefügt ist, dass Sie ein Mitglied von sind, finden Sie es unten und wählen Sie die Notifikationsmethoden aus, die Sie benutzen möchten. ",
"notifications:subscriptions:success" => "Ihre Notifikationseinstellungen sind gespart worden. ",

   );
   add_translation("de",$language);
   