<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "friends:all" => "Tutti gli amici",
"notifications:subscriptions:personal:description" => "Ricevere delle notifiche quando le azioni sono eseguite sul suo contenuto",
"notifications:subscriptions:personal:title" => "Notifiche personali",
"notifications:subscriptions:friends:title" => "Amici",
"notifications:subscriptions:friends:description" => "Sono di sotto delle collezioni dei suoi amici. Scegliere che una collezione accende delle notifiche per gli operatori in quella collezione. ",
"notifications:subscriptions:collections:edit" => "Per redigere le sue notifiche di accesso divise, lo scatto qui. ",
"notifications:subscriptions:changesettings" => "Notifiche",
"notifications:subscriptions:changesettings:groups" => "Raggruppare delle notifiche",
"notifications:subscriptions:title" => "Le notifiche per l'operatore",
"notifications:subscriptions:description" => "Per ricevere delle notifiche dai suoi amici (su una base individuale) quando creano il nuovo contenuto, trovarli di sotto e scegliere il metodo di notifica lei amerebbe usare. ",
"notifications:subscriptions:groups:description" => "Per ricevere delle notifiche quando il nuovo contenuto è aggiunto a un gruppo lei è membro di, lo trova di sotto e scegliere i metodi di notifica lei amerebbe usare. ",
"notifications:subscriptions:success" => "I suoi montaggi di notifiche sono stati risparmiati. ",

   );
   add_translation("it",$language);
   