<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "twitter:title" => "Twitter",
"twitter:info" => "Stellen Sie Ihre spätesten Zwitschern dar",
"twitter:username" => "Ihr Gezwitscherbenutzername",
"twitter:num" => "Zahl von Zwitschern zu zeigen*",
"twitter:visit" => "Besuchen Sie mein Gezwitscher",
"twitter:notset" => "Dieses Produkt muss gestaltet werden. Um Ihre spätesten Zwitschern darzustellen, klicken Sie das anpasst Abbild und Fülle in Ihrem Twitter Benutzernamen. ",
"twitter:invalid" => "Dieses Produkt ist mit einem ungültigen Twitter Benutzernamen gestaltet. Klicken Sie das anpasst Abbild, es zu korrigieren. ",
"twitter:apibug" => "*Auf Grund einer Wanze im Twitter 1,0 API, Sie dürfen wenigere Zwitschern sehen als Sie bitten um. ",

   );
   add_translation("de",$language);
   