<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "twitter:title" => "Cinguettio",
"twitter:info" => "Mostrare i suoi cinguetti recentissimi",
"twitter:username" => "Il suo nome utente di cinguettio",
"twitter:num" => "Il numero di cinguetti di mostrare*",
"twitter:visit" => "visitare il mio cinguettio",
"twitter:notset" => "Questo prodotto promozionale deve essere configurato. Per mostrare i suoi cinguetti recentissimi, scattare il di personalizzare l'icona e riempire il suo nome utente di Cinguettio. ",
"twitter:invalid" => "Questo prodotto promozionale è configurato con un nome utente di Cinguettio di invalido. Scattare il di personalizzare l'icona per correggerlo. ",
"twitter:apibug" => "*Dovuto a un insetto nel Cinguettio 1,0 API, lei potrebbe vedere meno cinguetti di lei chiede. ",

   );
   add_translation("it",$language);
   