<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "blog" => "Blogs",
"blog:blogs" => "Blogs",
"blog:revisions" => "Revisionen",
"blog:archives" => "Archive",
"blog:blog" => "Blog",
"item:object:blog" => "Blogs",
"blog:title:user_blogs" => "%die Blogs von s",
"blog:title:all_blogs" => "Alle Stelle bloggt",
"blog:title:friends" => "Die Blogs von Freunden",
"blog:group" => "Gruppenblog",
"blog:enableblog" => "Ermöglichen Sie Gruppenblog",
"blog:write" => "Schreiben Sie einen Blogposten",
"blog:add" => "Fügen Sie Blogposten hinzu",
"blog:edit" => "Redigieren Sie Blogposten",
"blog:excerpt" => "Exzerpt",
"blog:body" => "Körper",
"blog:save_status" => "Zuletzt gespart: ",
"blog:never" => "Nie",
"blog:status" => "Status",
"blog:status:draft" => "Entwurf",
"blog:status:published" => "Herausgegeben",
"blog:status:unsaved_draft" => "Entwerfen Sie Unsaved",
"blog:revision" => "Revision",
"blog:auto_saved_revision" => "Auto Hat Revision Gespart",
"blog:message:saved" => "Bloggen Sie gesparten Posten. ",
"blog:error:cannot_save" => "Kann Blogposten nicht sparen. ",
"blog:error:cannot_write_to_container" => "Unzureichender Zugang, Blog zu sparen, zu gruppieren. ",
"blog:messages:warning:draft" => "Es gibt einen unsaved Entwurf dieses Postens! ",
"blog:edit_revision_notice" => "(Alte Version)",
"blog:message:deleted_post" => "Bloggen Sie gelöschten Posten. ",
"blog:error:cannot_delete_post" => "Kann Blogposten nicht löschen. ",
"blog:none" => "Kein Blog stellt auf",
"blog:error:missing:title" => "Bitte tragen Sie einen Blogtitel ein! ",
"blog:error:missing:description" => "Bitte tragen Sie den Körper Ihres Blogs ein! ",
"blog:error:cannot_edit_post" => "Dieser Posten darf nicht existieren oder Sie dürfen Erlaubnis nicht haben, es zu redigieren. ",
"blog:error:revision_not_found" => "Kann diese Revision nicht finden. ",
"river:create:object:blog" => "%s hat herausgegeben einen Blogposten%s",
"river:comment:object:blog" => "%s hat kommentiert auf dem Blog%s",
"blog:newpost" => "Ein neuer Blogposten",
"blog:notification" => "%s hat gemacht einen neuen Blogposten. 

%s%s

Blick und kommentiert auf dem neuen Blogposten: %s

",
"blog:widget:description" => "Stellen Sie Ihre spätesten Blogposten dar",
"blog:moreblogs" => "Mehr Blog stellt auf",
"blog:numbertodisplay" => "Zahl von Blogposten, darzustellen",
"blog:noblogs" => "Kein Blog stellt auf",

   );
   add_translation("de",$language);
   