<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "blog" => "Blog",
"blog:blogs" => "Blog",
"blog:revisions" => "Revisioni",
"blog:archives" => "Archivio",
"blog:blog" => "Blog",
"item:object:blog" => "Blog",
"blog:title:user_blogs" => "%s scrive blog",
"blog:title:all_blogs" => "Tutto il luogo scrive blog",
"blog:title:friends" => "Blog di amici",
"blog:group" => "Raggruppare il blog",
"blog:enableblog" => "Permettere il blog di gruppo",
"blog:write" => "Scrivere blog il palo",
"blog:add" => "Aggiungere il palo di blog",
"blog:edit" => "Redigere il palo di blog",
"blog:excerpt" => "Estratto",
"blog:body" => "Corpo",
"blog:save_status" => "In ultimo risparmiato: ",
"blog:never" => "Mai",
"blog:status" => "Stato",
"blog:status:draft" => "Abbozzo",
"blog:status:published" => "Pubblicato",
"blog:status:unsaved_draft" => "Abbozzo non salvato",
"blog:revision" => "Revisione",
"blog:auto_saved_revision" => "L'automobile Ha Risparmiato Revisione",
"blog:message:saved" => "Scrivere blog il palo risparmiato. ",
"blog:error:cannot_save" => "Non risparmiarà il palo di blog. ",
"blog:error:cannot_write_to_container" => "L'accesso insufficiente di risparmiare il blog per raggruppare. ",
"blog:messages:warning:draft" => "C'è un abbozzo non salvato di questo palo! ",
"blog:edit_revision_notice" => "(La vecchia versione)",
"blog:message:deleted_post" => "Scrivere blog il palo cancellato. ",
"blog:error:cannot_delete_post" => "Non cancellarà il palo di blog. ",
"blog:none" => "Non affigge alcun blog",
"blog:error:missing:title" => "Per favore di entrare un titolo di blog! ",
"blog:error:missing:description" => "Per favore di entrare il corpo del suo blog! ",
"blog:error:cannot_edit_post" => "Questo palo non potrebbe esistere o lei non potrebbe avere dei permessi per redigerlo. ",
"blog:error:revision_not_found" => "Non trovarà questa revisione. ",
"river:create:object:blog" => "%s ha pubblicato un palo di blog %s",
"river:comment:object:blog" => "%s ha commentato il blog %s",
"blog:newpost" => "Un nuovo palo di blog",
"blog:notification" => "%s ha fatto un nuovo palo di blog. 

%s %s

La veduta e commenta il nuovo palo di blog: %s

",
"blog:widget:description" => "Mostrare i suoi pali di blog recentissimi",
"blog:moreblogs" => "Più blog affigge",
"blog:numbertodisplay" => "Il numero di pali di blog di mostrare",
"blog:noblogs" => "Non affigge alcun blog",

   );
   add_translation("it",$language);
   