<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "tinymce:remove" => "Entfernen Sie Redakteur",
"tinymce:add" => "Fügen Sie Redakteur hinzu",
"tinymce:word_count" => "Formulieren Sie Zahl: ",
"tinymce:lang_notice" => 'Ihre Stellensprache ist%s aber es ist für TinyMCE nicht installiert. Erhalten Sie es <a target="_blank" href=„%s“>Hier</a> Und kopieren Sie es zu%s. Dann <a href=\"%s\">Spülen Sie die Cachespeicher</a>. Siehe der TinyMCE README für mehr Details.',

   );
   add_translation("de",$language);
   