<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "tinymce:remove" => "Togliere l'editore",
"tinymce:add" => "Aggiungere l'editore",
"tinymce:word_count" => "Il conto di parola: ",
"tinymce:lang_notice" => 'La sua lingua di luogo è %s ma non è installato per TinyMCE. Prenderlo <a target="_blank" href=„%s“>qui</a> E lo copia a %s. Poi, <a href=\"%s\">sciacquare i nascondigli</a>. Vedere il TinyMCE README per più dettagli.',

   );
   add_translation("it",$language);
   