<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "item:object:reported_content" => "Berichtete Dinge",
"admin:administer_utilities:reportedcontent" => "Berichteten befriedigt",
"reportedcontent" => "Berichteten befriedigt",
"reportedcontent:this" => "Berichten Sie dies",
"reportedcontent:this:tooltip" => "Berichten Sie diese Seite zu einem Verwalter",
"reportedcontent:none" => "Es gibt keinen berichteten Inhalt",
"reportedcontent:report" => "Berichten Sie dies",
"reportedcontent:title" => "Seitentitel",
"reportedcontent:deleted" => "Der berichtete Inhalt ist gelöscht worden",
"reportedcontent:notdeleted" => "Wir konnten nicht jenes berichtet löschen",
"reportedcontent:delete" => "Löschen Sie Bericht",
"reportedcontent:areyousure" => "Sind Sie sicher Sie löschen wollen? ",
"reportedcontent:archive" => "Archivieren Sie Bericht",
"reportedcontent:archived" => "Der Bericht ist archiviert worden",
"reportedcontent:visit" => "Besuch hat Ding berichtet",
"reportedcontent:by" => "Berichten Sie durch",
"reportedcontent:objecttitle" => "Seitentitel",
"reportedcontent:objecturl" => "Seitenurl",
"reportedcontent:reason" => "Denken Sie logisch für Bericht",
"reportedcontent:description" => "Warum berichten Sie dies? ",
"reportedcontent:address" => "Ort des Dings",
"reportedcontent:success" => "Ihr Bericht ist zur Stellenadmin geschickt worden",
"reportedcontent:failing" => "Ihr Bericht könnte nicht geschickt werden",
"reportedcontent:moreinfo" => "Mehr Info",
"reportedcontent:instructions" => "Dieser Bericht wird zu den Verwaltern dieser Stelle für Nachprüfung geschickt werden. ",
"reportedcontent:numbertodisplay" => "Zahl von Berichten, darzustellen",
"reportedcontent:widget:description" => "Ausstellung hat befriedigt berichtet",
"reportedcontent:user" => "Berichtsverbraucher",
"reportedcontent:failed" => "Traurig, der Versuch zu berichten, dass dieser Inhalt versagt hat. ",
"reportedcontent:notarchived" => "Wir konnten nicht jenes berichtet archivieren",

   );
   add_translation("de",$language);
   