<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "item:object:reported_content" => "Articoli riferiti",
"admin:administer_utilities:reportedcontent" => "Contenuto riferito",
"reportedcontent" => "Contenuto riferito",
"reportedcontent:this" => "Riferire questo",
"reportedcontent:this:tooltip" => "Riferire questa pagina a un amministratore",
"reportedcontent:none" => "Non c'è alcun contenuto riferito",
"reportedcontent:report" => "Riferire questo",
"reportedcontent:title" => "Chiamare il titolo",
"reportedcontent:deleted" => "Il contenuto riferito è stato cancellato",
"reportedcontent:notdeleted" => "Non potevamo cancellare quella relazione",
"reportedcontent:delete" => "Cancellare la relazione",
"reportedcontent:areyousure" => "Lei è sicuro che lei vuole cancellare? ",
"reportedcontent:archive" => "Relazione di archivio",
"reportedcontent:archived" => "La relazione è stata archived",
"reportedcontent:visit" => "La visita ha riferito l'articolo",
"reportedcontent:by" => "Riferire da",
"reportedcontent:objecttitle" => "Chiamare il titolo",
"reportedcontent:objecturl" => "Chiamare URL",
"reportedcontent:reason" => "Ragionare per la relazione",
"reportedcontent:description" => "Perché lei riferisce questo? ",
"reportedcontent:address" => "La posizione dell'articolo",
"reportedcontent:success" => "La sua relazione è stata inviata all'ammin. di luogo",
"reportedcontent:failing" => "La sua relazione non potrebbe essere inviata",
"reportedcontent:moreinfo" => "Più informazioni",
"reportedcontent:instructions" => "Questa relazione sarà inviata agli amministratori di questo luogo per la revisione. ",
"reportedcontent:numbertodisplay" => "Il numero di relazioni di mostrare",
"reportedcontent:widget:description" => "La mostra ha riferito il contenuto",
"reportedcontent:user" => "Riferire l'operatore",
"reportedcontent:failed" => "Spiacente, il tentativo di riferire questo contenuto ha fallito. ",
"reportedcontent:notarchived" => "Non potevamo all'archivio quella relazione",

   );
   add_translation("it",$language);
   