<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "pages" => "Seiten",
"pages:owner" => "%die Seiten von s",
"pages:friends" => "Die Seiten von Freunden",
"pages:all" => "Alle Stelle paginiert",
"pages:add" => "Fügen Sie Seite hinzu",
"pages:group" => "Gruppenseiten",
"groups:enablepages" => "Ermöglichen Sie Gruppenseiten",
"pages:edit" => "Redigieren Sie diese Seite",
"pages:delete" => "Löschen Sie diese Seite",
"pages:history" => "Geschichte",
"pages:view" => "Siehe Seite an",
"pages:revision" => "Revision",
"pages:navigation" => "Navigation",
"pages:new" => "Eine neue Seite",
"pages:notification" => "%s hat hinzugefügt eine neue Seite: 

%s%s

Blick und kommentiert auf der neuen Seite: %s

",
"item:object:page_top" => "Hauptseiten",
"item:object:page" => "Seiten",
"pages:nogroup" => "Diese Gruppe hat keine Seiten noch",
"pages:more" => "Mehr Seiten",
"pages:none" => "Keine Seiten haben noch geschaffen",
"river:create:object:page" => "%s hat geschaffen eine Seite%s",
"river:create:object:page_top" => "%s hat geschaffen eine Seite%s",
"river:update:object:page" => "%s hat aktualisiert eine Seite%s",
"river:update:object:page_top" => "%s hat aktualisiert eine Seite%s",
"river:comment:object:page" => "%s hat kommentiert auf eine Seite hat genannt%s",
"river:comment:object:page_top" => "%s hat kommentiert auf eine Seite hat genannt%s",
"pages:title" => "Seitentitel",
"pages:description" => "Seitentext",
"pages:tags" => "Etikette",
"pages:parent_guid" => "Elternteilseite",
"pages:access_id" => "Lesen Sie Zugang",
"pages:write_access_id" => "Schreiben Sie Zugang",
"pages:noaccess" => "Kein Zugang, zu paginieren",
"pages:cantedit" => "Sie können diese Seite nicht redigieren",
"pages:saved" => "Paginieren Sie hat gespart",
"pages:notsaved" => "Seite könnte nicht gespart werden",
"pages:error:no_title" => "Sie müssen einen Titel für diese Seite angeben. ",
"pages:delete:success" => "Die Seite wurde erfolgreich gelöscht. ",
"pages:delete:failure" => "Die Seite könnte nicht gelöscht werden. ",
"pages:strapline" => "Zuletzt aktualisiert%s durch%s",
"pages:revision:subtitle" => "Revision hat geschaffen%s durch%s",
"pages:num" => "Zahl von Seiten, darzustellen",
"pages:widget:description" => "Dies ist eine Liste von Ihren Seiten. ",
"pages:label:view" => "Siehe Seite an",
"pages:label:edit" => "Redigieren Sie Seite",
"pages:label:history" => "Seitengeschichte",
"pages:sidebar:this" => "Diese Seite",
"pages:sidebar:children" => "U-Boot paginiert",
"pages:sidebar:parent" => "Elternteil",
"pages:newchild" => "Schaffen Sie eine U-Bootseite",
"pages:backtoparent" => "Zurück zu „%s“",

   );
   add_translation("de",$language);
   