<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "pages" => "Pagine",
"pages:owner" => "%s chiama",
"pages:friends" => "Pagine di amici",
"pages:all" => "Tutto il luogo chiama",
"pages:add" => "Aggiungere la pagina",
"pages:group" => "Il gruppo chiama",
"groups:enablepages" => "Permettere le pagine di gruppo",
"pages:edit" => "Redigere questa pagina",
"pages:delete" => "Cancellare questa pagina",
"pages:history" => "Storia",
"pages:view" => "Osservare la pagina",
"pages:revision" => "Revisione",
"pages:navigation" => "Navigazione",
"pages:new" => "Una nuova pagina",
"pages:notification" => "%s ha aggiunto una nuova pagina: 

%s %s

La veduta e commenta la nuova pagina: %s

",
"item:object:page_top" => "Pagine ad alto livello",
"item:object:page" => "Pagine",
"pages:nogroup" => "Questo gruppo non ha alcuna pagina ancora",
"pages:more" => "Più pagine",
"pages:none" => "Non ha creato alcuna pagina ancora",
"river:create:object:page" => "%s ha creato una pagina %s",
"river:create:object:page_top" => "%s ha creato una pagina %s",
"river:update:object:page" => "%s ha aggiornato una pagina %s",
"river:update:object:page_top" => "%s ha aggiornato una pagina %s",
"river:comment:object:page" => "%s ha commentato una pagina titolata %s",
"river:comment:object:page_top" => "%s ha commentato una pagina titolata %s",
"pages:title" => "Chiamare il titolo",
"pages:description" => "Chiamare il testo",
"pages:tags" => "Etichette",
"pages:parent_guid" => "Pagina di genitore",
"pages:access_id" => "Leggere l'accesso",
"pages:write_access_id" => "Scrivere l'accesso",
"pages:noaccess" => "Non chiamare alcun accesso",
"pages:cantedit" => "Lei non può redigere questa pagina",
"pages:saved" => "La pagina ha risparmiato",
"pages:notsaved" => "Non chiamare potrebbe essere risparmiato",
"pages:error:no_title" => "Lei deve specificare un titolo per questa pagina. ",
"pages:delete:success" => "La pagina è stata cancellata con successo. ",
"pages:delete:failure" => "La pagina non potrebbe essere cancellata. ",
"pages:strapline" => "In ultimo aggiornato %s da %s",
"pages:revision:subtitle" => "La revisione ha creato %s da %s",
"pages:num" => "Il numero di pagine di mostrare",
"pages:widget:description" => "Questo è un elenco delle sue pagine. ",
"pages:label:view" => "Osservare la pagina",
"pages:label:edit" => "Redigere la pagina",
"pages:label:history" => "Chiamare la storia",
"pages:sidebar:this" => "Questa pagina",
"pages:sidebar:children" => "Sotto-chiama",
"pages:sidebar:parent" => "Genitore",
"pages:newchild" => "Creare una sotto-pagina",
"pages:backtoparent" => "Di nuovo a „%s“",

   );
   add_translation("it",$language);
   