<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "logrotate:period" => "Wie oft sollte der Systemklotz archiviert werden? ",
"logrotate:weekly" => "Nachdem eine Woche",
"logrotate:monthly" => "Nachdem einen Monat",
"logrotate:yearly" => "Nachdem ein Jahr",
"logrotate:logrotated" => "Klotz hat gedreht",
"logrotate:lognotrotated" => "Fehler drehend Klotz",
"logrotate:delete" => "Löschen Sie hat archiviert Klötze älter als ein",
"logrotate:week" => "Woche",
"logrotate:month" => "Monat",
"logrotate:year" => "Jahr",
"logrotate:logdeleted" => "Klotz hat gelöscht",
"logrotate:lognotdeleted" => "Fehler löschend Klotz",

   );
   add_translation("de",$language);
   