<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "logrotate:period" => "Come spesso il ceppo di sistema dovrebbe essere archived? ",
"logrotate:weekly" => "Una volta alla settimana",
"logrotate:monthly" => "Una volta al mese",
"logrotate:yearly" => "Una volta all'anno",
"logrotate:logrotated" => "Il ceppo ha ruotato",
"logrotate:lognotrotated" => "L'errore che ruota il ceppo",
"logrotate:delete" => "Cancellare i ceppi di archived più vecchi di un",
"logrotate:week" => "settimana",
"logrotate:month" => "mese",
"logrotate:year" => "anno",
"logrotate:logdeleted" => "Il ceppo ha cancellato",
"logrotate:lognotdeleted" => "L'errore che cancella il ceppo",

   );
   add_translation("it",$language);
   