<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "bookmarks" => "Lesezeichen",
"bookmarks:add" => "Fügen Sie Lesezeichen hinzu",
"bookmarks:edit" => "Redigieren Sie Lesezeichen",
"bookmarks:owner" => "%die Lesezeichen von s",
"bookmarks:friends" => "Die Lesezeichen von Freunden",
"bookmarks:everyone" => "Alle Stellenlesezeichen",
"bookmarks:this" => "Lesezeichen diese Seite",
"bookmarks:this:group" => "Lesezeichen hinein%s",
"bookmarks:bookmarklet" => "Erhalten Sie bookmarklet",
"bookmarks:bookmarklet:group" => "Erhalten Sie gruppen bookmarklet",
"bookmarks:inbox" => "Lesezeichenposteingang",
"bookmarks:morebookmarks" => "Mehr Lesezeichen",
"bookmarks:more" => "Mehr Lesezeichen",
"bookmarks:with" => "Teilen Sie mit",
"bookmarks:new" => "Ein neues Lesezeichen",
"bookmarks:address" => "Adresse des Lesezeichens",
"bookmarks:none" => "Keine Lesezeichen",
"bookmarks:notification" => "%s hat hinzugefügt ein neues Lesezeichen: 

%s - %s%s

Blick und kommentiert auf dem neuen Lesezeichen: %s

",
"bookmarks:delete:confirm" => "Sind Sie sicher Sie löschen wollen diese Ressource? ",
"bookmarks:numbertodisplay" => "Zahl von Lesezeichen, darzustellen",
"bookmarks:shared" => "Bookmarked",
"bookmarks:visit" => "Besuchen Sie Ressource",
"bookmarks:recent" => "Neue Lesezeichen",
"river:create:object:bookmarks" => "%s bookmarked%s",
"river:comment:object:bookmarks" => "%s hat kommentiert auf einem Lesezeichen%s",
"bookmarks:river:annotate" => "Eine Bemerkung auf diesem Lesezeichen",
"bookmarks:river:item" => "Ein Ding",
"item:object:bookmarks" => "Lesezeichen",
"bookmarks:group" => "Gruppenlesezeichen",
"bookmarks:enablebookmarks" => "Ermöglichen Sie Gruppenlesezeichen",
"bookmarks:nogroup" => "Diese Gruppe hat keine Lesezeichen noch",
"bookmarks:no_title" => "Kein Titel",
"bookmarks:widget:description" => "Stellen Sie Ihre spätesten Lesezeichen dar. ",
"bookmarks:bookmarklet:description" => "Die Lesezeichen bookmarklet erlauben Ihnen, irgendeine Ressource zu teilen, die Sie auf dem Gewebe mit Ihren Freunden, oder nur Lesezeichen es für sich finden. Um es zu benutzen, einfach schleppen Sie den Folgenden Knopf zu den Verbindungen Ihres Browsers aussperrt: ",
"bookmarks:bookmarklet:descriptionie" => "Wenn Sie Internet Explorer benutzen, müssen Sie Klicken auf dem bookmarklet Abbild wieder gutmachen, auswählt ‚fügt zu Lieblingen hinzu‘, und dann die Verbindungen sperren aus. ",
"bookmarks:bookmarklet:description:conclusion" => "Sie können dann irgendeine Seite sparen, die Sie durch Klicken es jederzeit besuchen. ",
"bookmarks:save:success" => "Ihr Ding war erfolgreich bookmarked. ",
"bookmarks:delete:success" => "Ihr Lesezeichen wurde gelöscht. ",
"bookmarks:save:failed" => "Ihr Lesezeichen könnte nicht gespart werden. Vergewissern Sie sich, dass Sie einen Titel eingetragen haben, und redet an und versuchen Sie dann wieder. ",
"bookmarks:save:invalid" => "Die Adresse des Lesezeichens ist ungültig und könnte nicht gespart werden. ",
"bookmarks:delete:failed" => "Ihr Lesezeichen könnte nicht gelöscht werden. Bitte versuchen Sie wieder. ",

   );
   add_translation("de",$language);
   