<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "bookmarks" => "Segnalibri",
"bookmarks:add" => "Aggiungere il segnalibro",
"bookmarks:edit" => "Redigere il segnalibro",
"bookmarks:owner" => "%s i segnalibri",
"bookmarks:friends" => "Segnalibri di amici",
"bookmarks:everyone" => "Tutti i segnalibri di luogo",
"bookmarks:this" => "Il segnalibro questa pagina",
"bookmarks:this:group" => "Il segnalibro in %s",
"bookmarks:bookmarklet" => "Prendere il bookmarklet",
"bookmarks:bookmarklet:group" => "Prendere il bookmarklet di gruppo",
"bookmarks:inbox" => "Posta in arrivo di segnalibri",
"bookmarks:morebookmarks" => "Più segnalibri",
"bookmarks:more" => "Più segnalibri",
"bookmarks:with" => "Dividere con",
"bookmarks:new" => "Un nuovo segnalibro",
"bookmarks:address" => "L'indirizzo del segnalibro",
"bookmarks:none" => "Nessun segnalibri",
"bookmarks:notification" => "%s ha aggiunto un nuovo segnalibro: 

%s - %s %s

La veduta e commenta il nuovo segnalibro: %s

",
"bookmarks:delete:confirm" => "Lei è sicuro che lei vuole cancellare questa risorsa? ",
"bookmarks:numbertodisplay" => "Il numero di segnalibri di mostrare",
"bookmarks:shared" => "Bookmarked",
"bookmarks:visit" => "Visitare la risorsa",
"bookmarks:recent" => "Segnalibri recenti",
"river:create:object:bookmarks" => "%s il bookmarked %s",
"river:comment:object:bookmarks" => "%s ha commentato un segnalibro %s",
"bookmarks:river:annotate" => "un commento su questo segnalibro",
"bookmarks:river:item" => "un articolo",
"item:object:bookmarks" => "Segnalibri",
"bookmarks:group" => "Raggruppare dei segnalibri",
"bookmarks:enablebookmarks" => "Permettere i segnalibri di gruppo",
"bookmarks:nogroup" => "Questo gruppo non ha alcun segnalibro ancora",
"bookmarks:no_title" => "Nessun titolo",
"bookmarks:widget:description" => "Mostrare i suoi segnalibri recentissimi. ",
"bookmarks:bookmarklet:description" => "Il bookmarklet di segnalibri consente che dividere qualunque risorsa che lei trova sulla tela con i suoi amici o il suo appena segnalibro esso per te stesso. Per usarlo, semplicemente trascinare il bottone seguente alle maglie del suo browser sbarra: ",
"bookmarks:bookmarklet:descriptionie" => "Se lei usa Esploratore di Internet, lei dovrà ristabilire lo scatto sull'icona di bookmarklet, sceglie 'aggiunge ai favoriti' e poi le Maglie sbarrano. ",
"bookmarks:bookmarklet:description:conclusion" => "Lei può risparmiare poi qualunque pagina che lei visita lo scattando a qualunque tempo. ",
"bookmarks:save:success" => "Il suo articolo era con successo il bookmarked. ",
"bookmarks:delete:success" => "Il suo segnalibro è stato cancellato. ",
"bookmarks:save:failed" => "Il suo segnalibro non potrebbe essere risparmiato. Assicurarla è entrato un titolo ed un indirizzo e poi provare di nuovo. ",
"bookmarks:save:invalid" => "L'indirizzo del segnalibro è l'invalido e non potrebbe essere risparmiato. ",
"bookmarks:delete:failed" => "Il suo segnalibro non potrebbe essere cancellato. Per favore di provare di nuovo. ",

   );
   add_translation("it",$language);
   