<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "likes:this" => "Gemögen dies",
"likes:deleted" => "Ihres wie ist entfernt worden",
"likes:see" => "Siehe, wer dies gemocht hat",
"likes:remove" => "Ungleich dies",
"likes:notdeleted" => "Es gab ein Problem, das Ihres wie entfernt",
"likes:likes" => "Sie mögen jetzt dieses Ding",
"likes:failure" => "Es gab ein Problem, das dieses Ding mag",
"likes:alreadyliked" => "Sie haben schon dieses Ding gemocht",
"likes:notfound" => "Das Ding, das Sie versuchen, zu mögen, kann nicht gefunden werden",
"likes:likethis" => "Wie dies",
"likes:userlikedthis" => "%s wie",
"likes:userslikedthis" => "%s mag",
"likes:river:annotate" => "Mag",
"likes:delete:confirm" => "Sind Sie sicher Sie löschen wollen dieses wie? ",
"river:likes" => "Mag%s%s",
"likes:notifications:subject" => "%s mag Ihren Posten „%s“",
"likes:notifications:body" => "Hallo %1$s,

%2$s mag Ihren Posten „%3$s“ auf %4$s

Siehe Ihren ursprünglichen Posten hier: 

%5$s

Oder Siehe %2$s's Profil hier an: 

%6$s

Dank, %4$s

",

   );
   add_translation("de",$language);
   