<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "likes:this" => "amato questo",
"likes:deleted" => "Suo amando è stato tolto",
"likes:see" => "Vedere chi ha amato questo",
"likes:remove" => "A differenza di questo",
"likes:notdeleted" => "C'era un problema che toglie suo amando",
"likes:likes" => "Lei ama ora quest'articolo",
"likes:failure" => "C'era un problema che ama quest'articolo",
"likes:alreadyliked" => "Lei ha amato già quest'articolo",
"likes:notfound" => "L'articolo che lei non provano amare può essere trovato",
"likes:likethis" => "Come questo",
"likes:userlikedthis" => "%s come",
"likes:userslikedthis" => "%s ama",
"likes:river:annotate" => "ama",
'likes:delete:confirm' => 'Are you sure you want to delete this like?',
"river:likes" => "ama %s %s",
"likes:notifications:subject" => "%s ama il suo palo „%s“",
"likes:notifications:body" => 'Ciao "%1$s",

%2$s ama il suo palo "%3$s" su %4$s

Vedere il suo palo originale qui: 

"%5$s"

O osserva "%2$s"  il profilo qui: 

"%6$s"

I ringraziamenti, %4$s

',

   );
   add_translation("it",$language);
   