<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "embed:embed" => "Betten Sie ein",
"embed:media" => "Betten Sie Inhalt ein",
"embed:instructions" => "Klicken Sie irgendeine Datei an, es in Ihren Inhalt einzubetten. ",
"embed:upload" => "Laden Sie Medien",
"embed:upload_type" => "Laden Sie Typ: ",
"embed:no_upload_content" => "Kein Uploadinhalt! ",
"embed:no_section_content" => "Keine Dinge haben gefunden. ",
"embed:no_sections" => "Kein unterstütztes bettet plugins gefunden ein. Fragen Sie, dass der Stellenverwalter zu hat ermöglicht einen plugin mit einbettet Stütze. ",

   );
   add_translation("de",$language);
   