<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "embed:embed" => "Incassare",
"embed:media" => "Incassare il contenuto",
"embed:instructions" => "Scattare su qualunque file per incassarlo nel suo contenuto. ",
"embed:upload" => "Caricare dei mezzi di comunicazione",
"embed:upload_type" => "Caricare il tipo: ",
"embed:no_upload_content" => "Nessun contenuto di caricamento! ",
"embed:no_section_content" => "Non ha trovato alcun articolo. ",
"embed:no_sections" => "Nessun sostenuto incassa il plugins ha trovato. Chiedere l'amministratore di luogo a ha permesso un plugin con incassa il sostegno. ",

   );
   add_translation("it",$language);
   