<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "friends:invite" => "Laden Sie Freunde ein",
"invitefriends:registration_disabled" => "Neue Verbraucherregistrierung ist auf dieser Stelle gemacht worden unwirksam; Sie können nicht neue Verbraucher einladen. ",
"invitefriends:introduction" => "Um Freunde einzuladen, um Sie auf diesem Netz anzuschließen, tragen Sie ihre E-Mail-Adressen unten (einer pro Linie) ein: ",
"invitefriends:message" => "Tragen Sie eine Nachricht ein die sie werden empfangen mit Ihrer Einladung: ",
"invitefriends:subject" => "Einladung anzuschließen%s",
"invitefriends:success" => "Ihre Freunde wurden eingeladen. ",
"invitefriends:invitations_sent" => "Lädt geschickt ein: %s. Es gab die Folgenden Probleme: ",
"invitefriends:email_error" => "Die Folgenden Adressen sind nicht gültig: %s",
"invitefriends:already_members" => "Das Folgende ist schon Mitglieder: %s",
"invitefriends:noemails" => "Keine E-Mail-Adressen wurden eingetragen. ",
"invitefriends:message:default" => "Hallo,

Ich will Sie einladen, mein Netz hier an anzuschließen, %s. 

",
"invitefriends:email" => "Sie sind eingeladen worden anzuschließen%s durch%s. Sie haben die Folgende Nachricht eingeschlossen: 

%s

Um anzuschließen, klicken Sie die Folgende Verbindung: 

%s

Sie werden automatisch sie als ein Freund hinzufügen, wenn Sie Ihr Konto schaffen. 

",

   );
   add_translation("de",$language);
   