<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "friends:invite" => "Invitare degli amici",
"invitefriends:registration_disabled" => "La nuova iscrizione di operatore è stata stata incapace su questo luogo; lei non può invitare dei nuovi operatori. ",
"invitefriends:introduction" => "Per invitare degli amici a unirla su questa rete, entra i loro indirizzi e-mail di sotto (uno per la linea) : ",
"invitefriends:message" => "Entrare un messaggio che riceveranno con il suo invito: ",
"invitefriends:subject" => "L'invito di unire %s",
"invitefriends:success" => "I suoi amici sono stati invitati. ",
"invitefriends:invitations_sent" => "Invita inviato: %s. C'erano i problemi seguenti: ",
"invitefriends:email_error" => "Gli indirizzi seguenti non sono validi: %s",
"invitefriends:already_members" => "Il seguito è dei già membri: %s",
"invitefriends:noemails" => "Non è stato entrato alcun indirizzi e-mail. ",
"invitefriends:message:default" => "Ciao,

Voglio invitarla a unire la mia rete qui su %s. 

",
"invitefriends:email" => "Lei è stato invitato a unire %s da %s. Hanno incluso il messaggio seguente: 

%s

Per unire, scatta la maglia seguente: 

%s

Lei li aggiungerà automaticamente come un amico quando lei crea il suo conto. 

",

   );
   add_translation("it",$language);
   