<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "dashboard:widget:group:title" => "Gruppentätigkeit",
"dashboard:widget:group:desc" => "Siehe die Tätigkeit in einem von Ihren Gruppen an",
"dashboard:widget:group:select" => "Wählen Sie eine Gruppe aus",
"dashboard:widget:group:noactivity" => "Es gibt keine Tätigkeit in dieser Gruppe",
"dashboard:widget:group:noselect" => "Redigieren Sie dieses Produkt, eine Gruppe auszuwählen",

   );
   add_translation("de",$language);
   