<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "dashboard:widget:group:title" => "Raggruppare l'attività",
"dashboard:widget:group:desc" => "Osservare l'attività in uno dei suoi gruppi",
"dashboard:widget:group:select" => "Scegliere un gruppo",
"dashboard:widget:group:noactivity" => "Non ci è attività in questo gruppo",
"dashboard:widget:group:noselect" => "Redigere questo prodotto promozionale per scegliere un gruppo",

   );
   add_translation("it",$language);
   