<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "custom:bookmarks" => "Die spätesten Lesezeichen",
"custom:groups" => "Die spätesten Gruppen",
"custom:files" => "Die spätesten Dateien",
"custom:blogs" => "Das späteste Blog stellt auf",
"custom:members" => "Die neusten Mitglieder",

   );
   add_translation("de",$language);
   