<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "custom:bookmarks" => "Segnalibri recentissimi",
"custom:groups" => "Gruppi recentissimi",
"custom:files" => "File recentissimi",
"custom:blogs" => "Il blog recentissimo affigge",
"custom:members" => "I più nuovi membri",

   );
   add_translation("it",$language);
   