<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "messages" => "Nachrichten",
"messages:unreadcount" => "%s ungelesen",
"messages:back" => "Zurück zu Nachrichten",
"messages:user" => "%der Posteingang von s",
"messages:posttitle" => "%die Nachrichten von s: %s",
"messages:inbox" => "Posteingang",
"messages:send" => "Schicken Sie",
"messages:sent" => "Geschickt",
"messages:message" => "Nachricht",
"messages:title" => "Thema",
"messages:to" => "Zu",
"messages:from" => "Von",
"messages:fly" => "Schicken Sie",
"messages:replying" => "Nachrichterwiderung zu",
"messages:sendmessage" => "Schicken Sie eine Nachricht",
"messages:compose" => "Setzen Sie eine Nachricht zusammen",
"messages:add" => "Setzen Sie eine Nachricht zusammen",
"messages:sentmessages" => "Geschickte Nachrichten",
"messages:recent" => "Neue Nachrichten",
"messages:original" => "Ursprüngliche Nachricht",
"messages:yours" => "Ihre Nachricht",
"messages:answer" => "Antwort",
"messages:toggle" => "Schalten Sie alle um",
"messages:markread" => "Markieren Sie Vorlesung",
"messages:recipient" => "Wählen Sie einen Empfänger",
"messages:to_user" => "Zu: %s",
"messages:new" => "Neue Nachricht",
"notification:method:site" => "Stelle",
"messages:error" => "Es gab ein Problem, das Ihre Nachricht spart. Bitte versuchen Sie wieder. ",
"item:object:messages" => "Nachrichten",
"messages:posted" => "Ihre Nachricht wurde erfolgreich geschickt. ",
"messages:success:delete:single" => "Nachricht wurde gelöscht",
"messages:success:delete" => "Nachrichten haben gelöscht",
"messages:success:read" => "Nachrichten haben als Vorlesung markiert",
"messages:error:messages_not_selected" => "Keine Nachrichten haben ausgewählt",
"messages:error:delete:single" => "Unfähig, die Nachricht zu löschen",
"messages:email:subject" => "Sie haben eine neue Nachricht! ",
"messages:email:body" => "Sie haben eine neue Nachricht von%s. Es liest: 

%s

Um Ihre Nachrichten anzusehen, Klicken hier: 

%s

Zu schicken%s eine Nachricht, Klicken hier: 

%s

Sie können zu dieser E-Mail nicht antworten. 

",
"messages:blank" => "Traurig; Sie brauchen tatsächlich, etwas in den Nachrichtkörper zu stellen, bevor wir es sparen können. ",
"messages:notfound" => "Traurig; wir könnten die angegebene Nachricht nicht finden. ",
"messages:notdeleted" => "Traurig; wir könnten diese Nachricht nicht löschen. ",
"messages:nopermission" => "Sie haben nicht Erlaubnis, jene Nachricht zu verändern. ",
"messages:nomessages" => "Es gibt keine Nachrichten. ",
"messages:user:nonexist" => "Wir könnten den Empfänger in der Verbraucherdatenbank nicht finden. ",
"messages:user:blank" => "Sie haben niemanden ausgewählt, dies zu zu schicken. ",
"messages:deleted_sender" => "Gelöschten Verbraucher",

   );
   add_translation("de",$language);
   