<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "messages" => "Messaggi",
"messages:unreadcount" => "%s incolto",
"messages:back" => "di nuovo ai messaggi",
"messages:user" => "%s la posta in arrivo",
"messages:posttitle" => "%s i messaggi: %s",
"messages:inbox" => "Posta in arrivo",
"messages:send" => "Inviare",
"messages:sent" => "Inviato",
"messages:message" => "Messaggio",
"messages:title" => "Soggetto",
"messages:to" => "A",
"messages:from" => "Da",
"messages:fly" => "Inviare",
"messages:replying" => "Il messaggio che risponde a",
"messages:sendmessage" => "Inviare un messaggio",
"messages:compose" => "Comporre un messaggio",
"messages:add" => "Comporre un messaggio",
"messages:sentmessages" => "Messaggi inviati",
"messages:recent" => "Messaggi recenti",
"messages:original" => "Messaggio originale",
"messages:yours" => "Il suo messaggio",
"messages:answer" => "Risposta",
"messages:toggle" => "Commutare tutto",
"messages:markread" => "Il marchio ha letto",
"messages:recipient" => "Scegliere un destinatario",
"messages:to_user" => "A: %s",
"messages:new" => "Nuovo messaggio",
"notification:method:site" => "Luogo",
"messages:error" => "C'era un problema che risparmia il suo messaggio. Per favore di provare di nuovo. ",
"item:object:messages" => "Messaggi",
"messages:posted" => "Il suo messaggio è stato inviato con successo. ",
"messages:success:delete:single" => "Il messaggio è stato cancellato",
"messages:success:delete" => "I messaggi hanno cancellato",
"messages:success:read" => "I messaggi hanno marcato poiché leggono",
"messages:error:messages_not_selected" => "Non ha scelto alcun messaggio",
"messages:error:delete:single" => "Incapace per cancellare il messaggio",
"messages:email:subject" => "Lei ha un nuovo messaggio! ",
"messages:email:body" => "Lei ha un nuovo messaggio da %s. Legge: 

%s

Per osservare i suoi messaggi, il suo scatto qui: 

%s

Per inviare %s un messaggio, uno scatto qui: 

%s

Lei non può rispondere a quest'e-mail. 

",
"messages:blank" => "Spiacente; lei ha bisogno di effettivamente mettere qualcosa nel corpo di messaggio prima che potessimo risparmiarlo. ",
"messages:notfound" => "Spiacente; non potremmo trovare il messaggio specificato. ",
"messages:notdeleted" => "Spiacente; non potremmo cancellare questo messaggio. ",
"messages:nopermission" => "Lei non ha il permesso per alterare quel messaggio. ",
"messages:nomessages" => "Non ci è messaggi. ",
"messages:user:nonexist" => "Non potremmo trovare il destinatario nella base di dati di operatore. ",
"messages:user:blank" => "Lei non ha scelto qualcuno per inviare questo a. ",
"messages:deleted_sender" => "Operatore cancellato",

   );
   add_translation("it",$language);
   