<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "admin:administer_utilities:diagnostics" => "Systemdiagnose",
"diagnostics" => "Systemdiagnose",
"diagnostics:report" => "Diagnosebericht",
"diagnostics:description" => "Das, das diagnostischem Bericht folgt, kann nützlich sein für Diagnostizierenprobleme mit Elgg. Die Entwickler des Elgg dürfen erbitten, dass Sie es zu einem Wanzenbericht befestigen. ",
"diagnostics:download" => "Download",
"diagnostics:header" => "======================================================================== Diagnostisch Elgg Berichten Sie Hat
Erzeugt%s durch%s ========================================================================

",
"diagnostics:report:basic" => "Elgg Entlassung%s, Version%s

----------------------------------------------------------------------. --

",
"diagnostics:report:php" => "PHP Info: %s ----------------------------------------------------------------------. --",
"diagnostics:report:plugins" => "Installiert plugins und detailliert: 

%s ----------------------------------------------------------------------. --

",
"diagnostics:report:md5" => "Installierte Dateien und checksums: 

%s ----------------------------------------------------------------------. --

",
"diagnostics:report:globals" => "Globale Variablen: 

%s ----------------------------------------------------------------------. --

",

   );
   add_translation("de",$language);
   