<?php 
/** LiangLee MultiLanguage
 * Framework for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeeMultiLanguage
 * @author Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @copyright Copyright 2013, Liang Lee
 */
   $language = array(
   "admin:administer_utilities:diagnostics" => "Diagnostici di sistema",
"diagnostics" => "Diagnostici di sistema",
"diagnostics:report" => "Relazione di diagnostici",
"diagnostics:description" => "La relazione seguente diagnostica può essere utile per diagnosticare di problemi con Elgg. Gli sviluppatori di Elgg potrebbero richiedere che lei l'attacca a una relazione di insetto. ",
"diagnostics:download" => "Scaricare",
"diagnostics:header" => "======================================================================== Elgg la Relazione Diagnostica Ha
Generato %s da %s ========================================================================

",
"diagnostics:report:basic" => "La Liberazione di Elgg %s, la versione %s

----------------------------------------------------------------------. --

",
"diagnostics:report:php" => "Le informazioni di PHP: %s ----------------------------------------------------------------------. --",
"diagnostics:report:plugins" => "Il plugins installato e dettaglia: 

%s ----------------------------------------------------------------------. --

",
"diagnostics:report:md5" => "I file installati ed i totali di verifica: 

%s ----------------------------------------------------------------------. --

",
"diagnostics:report:globals" => "Le variabili globali: 

%s ----------------------------------------------------------------------. --

",

   );
   add_translation("it",$language);
   